# Generated by Django 2.1 on 2019-01-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ja', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='group.Group')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['order', 'id'],
            },
        ),
    ]
