# Generated by Django 2.1 on 2018-12-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_url',
            new_name='image',
        ),
    ]
