# Generated by Django 2.1 on 2018-12-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='introductionen',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
