# Generated by Django 2.1 on 2018-09-04 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=2)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('event_url', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('published_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'topic',
                'ordering': ['-id', '-published_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=2)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('event_url', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('published_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'topic_en',
                'ordering': ['-id', '-published_at'],
                'abstract': False,
            },
        ),
    ]
