# Generated by Django 2.1 on 2019-01-23 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('topic', 'topic'), ('event', 'event')], default='topic', max_length=255, null=True)),
                ('new', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=2)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('button_label', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('published_at', models.DateTimeField(default=datetime.datetime.now)),
                ('images', models.ManyToManyField(blank=True, to='extra.Image')),
            ],
            options={
                'db_table': 'topic',
                'ordering': ['-id', '-published_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('topic', 'topic'), ('event', 'event')], default='topic', max_length=255, null=True)),
                ('new', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=2)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('button_label', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('published_at', models.DateTimeField(default=datetime.datetime.now)),
                ('images', models.ManyToManyField(blank=True, to='extra.Image')),
            ],
            options={
                'db_table': 'topic_en',
                'ordering': ['-id', '-published_at'],
                'abstract': False,
            },
        ),
    ]
