# Generated by Django 2.1 on 2018-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='body',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='topicen',
            old_name='body',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='image_url',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='topicen',
            old_name='image_url',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='event_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='topicen',
            old_name='event_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='topic',
            name='button_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='images',
            field=models.ManyToManyField(blank=True, to='extra.Image'),
        ),
        migrations.AddField(
            model_name='topicen',
            name='button_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topicen',
            name='images',
            field=models.ManyToManyField(blank=True, to='extra.Image'),
        ),
    ]
