# Generated by Django 2.1 on 2018-12-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20181210_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='new_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='post_type',
            field=models.CharField(blank=True, choices=[('topic', 'topic'), ('event', 'event')], default='topic', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topicen',
            name='new_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicen',
            name='post_type',
            field=models.CharField(blank=True, choices=[('topic', 'topic'), ('event', 'event')], default='topic', max_length=255, null=True),
        ),
    ]
