# Generated by Django 2.1 on 2019-01-08 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20181210_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='topicen',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
