# Generated by Django 2.1 on 2018-12-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='body',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='videoen',
            old_name='body',
            new_name='text',
        ),
    ]
