# Generated by Django 2.1 on 2018-12-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20181210_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='videoen',
            name='pickup',
        ),
    ]
